
public enum ResponseType {
	LOGIN_SUCCESS, LOGIN_FAIL, PLACE_BET_SUCCESS,
	PLACE_BET_FAIL, WITHDRAW_SUCCESS, WITHDRAW_FAIL,
	DEALER, PLAYER, GAME_STATE, PLAYER_TURN,ROUND_DONE, ALL_BETS, PLAYER_TURN_END, ALL_PLAYERS_DONE, 
	REQUEST_DEALER_HIT, REQUEST_END_ROUND,REQUEST_START_ROUND, UPDATE, CURR_PLAYER, UNKNOWN;
}
